version: '3'
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'postgres@2022'
        ports:
            - '15432:5432'
        volumes:
            - ~/tmp/postgres:/var/lib/postgresql/data