version: '3'
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'postgres@2022'
        ports:
            - '15432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - postgres-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
            PGADMIN_DEFAULT_PASSWORD: 'postgres@2022'
        ports:
            - '16543:80'
        depends_on:
            - postgres
        networks:
            - postgres-network
    api:
        build: .
        command: npm start
        ports:
            - '5000:5000'
        volumes:
            - .:/usr/app

networks:
    postgres-compose-network:
        driver: bridge
