version: '3'
services:
    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'postgres@2022'
        ports:
            - '15432:5432'
        volumes:
            - /temp/postgres:/var/lib/postgresql/data
        networks:
            - e-commerce
    api:
        build: .
        depends_on:
            - database
        ports:
            - '8080:3000'
        restart: on-failure
        networks:
            - e-commerce
networks:
    e-commerce:
        driver: bridge
